### PR TITLE
Replace new Bip32() with new this.constructor()

### PR DESCRIPTION
**Pull request by shruggr**

### CODE REVIEW

**Comment by shruggr** [comment]
#156

**Comment by ryanxcharles** [comment]
LGTM. However, you modified a bunch of function definitions to get rid of the space which is going to break the linter.

**Comment by shruggr** [comment]
I was just noticing that. My editor introduced whitespace. Sorry about that. I'll get it fixed

**Comment by ryanxcharles** [comment]
If you fix this, note that you can push new commits to the same branch without closing the PR. It is better to use the same PR so people can track the discussion.

**Pull request closed without merging**
