### PR TITLE
Optimization for size of bsv.min.js

### PR DESCRIPTION
**Pull request by monkeylord**
Replace the whole lodash library to a collection of single functions.
size of the output `bsv.min.js` is reduced from 534KB to 499KB.

### CODE REVIEW

**Comment by monkeylord** [comment]
removed bs58 library by implement base58 directly.
removed dependency of nodejs native crypto hash library by introduce a pure js hash.js library.
We can get rid of the huge compatible browserify-crypto library now.

**Comment by monkeylord** [comment]
It's very happy to find hash.js is already included in `elliptic`, which means we introduce no new library actually.

**Comment by ryanxcharles** [comment]
this is fantastic. however, two of your changes have speed implications:
- how fast is your base 58 implementation compared to bs58?
- how fast is hash.js compared to the node.js hash functions?

**Comment by monkeylord** [comment]
> this is fantastic. however, two of your changes have speed implications:
> 
> * how fast is your base 58 implementation compared to bs58?
> * how fast is hash.js compared to the node.js hash functions?

I use BN to do div/mod while bs58 use some bit manipulation.
However, there should not be too much speed difference because BN do the similar manipulation.

For hash.js, in nodejs, it should be difference between javascript code and native code, while in browser it should be no difference because they are both javascript code.

I don't know how to test it, but I think bottleneck is ECDSA.

**Comment by ryanxcharles** [comment]
we need to see benchmarks of the base58 implications before merging. we use this extensively in production and do not want to make things slower.

**Comment by monkeylord** [comment]
Base58 Benchmark Result show bs58 is indeed faster.
While bs58 will only result 2KB larger, I'll get it back.

Base58 with BN
~~~
Benchmark
Base58
  new Base58() : 1000000 times - 0ms
  Base58() : 1000000 times - 16ms
  validates characters : 1000000 times - 9437ms
  validates characters from buffer : 1000000 times - 9923ms
  some characters are invalid : 1000000 times - 2094ms
  handy syntax : 1000000 times - 7031ms
#set
  set a blank buffer : 1000000 times - 94ms
@encode
  encode the buffer : 1000000 times - 2297ms
@decode
  decode this encoded value : 1000000 times - 3843ms
#fromBuffer
  set buffer : 1000000 times - 281ms
@fromBuffer
  set buffer : 1000000 times - 266ms
@fromHex
  set buffer : 1000000 times - 641ms
#fromString
  convert this known string to a buffer : 1000000 times - 4204ms
#fromString
  convert this known string to a buffer : 1000000 times - 4576ms
#toBuffer
  return the buffer : 1000000 times - 299ms
#toHex
  return the hex : 1000000 times - 296ms
#toString
  return the buffer : 1000000 times - 2282ms
~~~

Base58 with bs58
~~~
Benchmark
Base58
  new Base58() : 1000000 times - 0ms
  Base58() : 1000000 times - 32ms
  validates characters : 1000000 times - 13322ms
  validates characters from buffer : 1000000 times - 13844ms
  some characters are invalid : 1000000 times - 3572ms
  handy syntax : 1000000 times - 1459ms
#set
  set a blank buffer : 1000000 times - 106ms
@encode
  encode the buffer : 1000000 times - 225ms
@decode
  decode this encoded value : 1000000 times - 1082ms
#fromBuffer
  set buffer : 1000000 times - 297ms
@fromBuffer
  set buffer : 1000000 times - 281ms
@fromHex
  set buffer : 1000000 times - 672ms
#fromString
  convert this known string to a buffer : 1000000 times - 1096ms
#fromString
  convert this known string to a buffer : 1000000 times - 1078ms
#toBuffer
  return the buffer : 1000000 times - 299ms
#toHex
  return the hex : 1000000 times - 296ms
#toString
  return the buffer : 1000000 times - 235ms
~~~


Script:
~~~javascript
var bsv = require('./')
var Base58 = bsv.encoding.Base58
var buffer = require('buffer')
console.log('Benchmark')

var buf = Buffer.from([0, 1, 2, 3, 253, 254, 255])
var enc = '1W7N4RuG'

function benchmark(info,func){
    var starttime = new Date().getTime()
    for(var i=0;i<1000000;i++)func()
    var endtime = new Date().getTime()
    console.log(`  ${info} : 1000000 times - ${endtime-starttime}ms`)
}

function describe(info,func){
    console.log(info)
    func()
}

describe('Base58', function () {
  var buf = Buffer.from([0, 1, 2, 3, 253, 254, 255])
  var enc = '1W7N4RuG'

  benchmark('new Base58()', function () {
    var b58 = new Base58()
  })
  
  benchmark('Base58()', function () {
    var b58 = Base58()
  })
  
  benchmark('validates characters', function () {
    Base58.validCharacters(
      '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'
    )
  })
  benchmark('validates characters from buffer', function () {
    Base58.validCharacters(
      buffer.Buffer.from('123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz')
    )
  })

  benchmark('some characters are invalid', function () {
    Base58.validCharacters('!@#%^$&*()\\')
  })

  benchmark('handy syntax', function () {
    Base58(buf).toString()==(enc)
    Base58(enc).toBuffer().toString('hex')==(buf.toString('hex'))
  })

  describe('#set', function () {
    benchmark('set a blank buffer', function () {
      Base58().set({
        buf: buffer.Buffer.from([])
      })
    })
  })

  describe('@encode', function () {
    benchmark('encode the buffer', function () {
      Base58.encode(buf)==(enc)
    })
  })

  describe('@decode', function () {
    benchmark('decode this encoded value', function () {
      Base58.decode(enc).toString('hex')==(buf.toString('hex'))
    })
  })

  describe('#fromBuffer', function () {
    benchmark('set buffer', function () {
      var b58 = Base58().fromBuffer(buf)
      b58.buf.toString('hex')==(buf.toString('hex'))
    })
  })

  describe('@fromBuffer', function () {
    benchmark('set buffer', function () {
      var b58 = Base58.fromBuffer(buf)
      b58.toHex()==(buf.toString('hex'))
    })
  })

  describe('@fromHex', function () {
    benchmark('set buffer', function () {
      var b58 = Base58.fromHex(buf.toString('hex'))
      b58.buf.toString('hex')==(buf.toString('hex'))
    })
  })

  describe('#fromString', function () {
    benchmark('convert this known string to a buffer', function () {
      Base58().fromString(enc).toBuffer().toString('hex')==(buf.toString('hex'))
    })
  })

  describe('#fromString', function () {
    benchmark('convert this known string to a buffer', function () {
      Base58.fromString(enc).toBuffer().toString('hex')==(buf.toString('hex'))
    })
  })

  describe('#toBuffer', function () {
    benchmark('return the buffer', function () {
      var b58 = Base58(buf)
      b58.buf.toString('hex')==(buf.toString('hex'))
    })
  })

  describe('#toHex', function () {
    benchmark('return the hex', function () {
      var b58 = Base58(buf)
      b58.toHex()==(buf.toString('hex'))
    })
  })

  describe('#toString', function () {
    benchmark('return the buffer', function () {
      var b58 = Base58(buf)
      b58.toString()==(enc)
    })
  })
})
~~~

**Comment by monkeylord** [comment]
Well, Hash is 2-5 times slower than the native hash function.
Hash.js
~~~
Benchmark
Hash
@sha1
  calculates the hash of this buffer correctly : 1000000 times - 8755ms
#sha256
  calculates the hash of this buffer correctly : 1000000 times - 5668ms
#sha256hmac
  computes this known big key correctly : 1000000 times - 31561ms
  computes this known empty test vector correctly : 1000000 times - 19517ms
  computes this known non-empty test vector correctly : 1000000 times - 20250ms
#sha256sha256
  calculates the hash of this buffer correctly : 1000000 times - 11111ms
#sha256ripemd160
  calculates the hash of this buffer correctly : 1000000 times - 9952ms
#ripemd160
  calculates the hash of this buffer correctly : 1000000 times - 4343ms
#sha512
  calculates the hash of this buffer correctly : 1000000 times - 12828ms
#sha512hmac
  calculates this known empty test vector correctly : 1000000 times - 48577ms
  calculates this known non-empty test vector correctly : 1000000 times - 50391ms
~~~
Nodejs Native
~~~
Benchmark
Hash
@sha1
  calculates the hash of this buffer correctly : 1000000 times - 4079ms
#sha256
  calculates the hash of this buffer correctly : 1000000 times - 1953ms
#sha256hmac
  computes this known big key correctly : 1000000 times - 11080ms
  computes this known empty test vector correctly : 1000000 times - 8968ms
  computes this known non-empty test vector correctly : 1000000 times - 9516ms
#sha256sha256
  calculates the hash of this buffer correctly : 1000000 times - 3281ms
#sha256ripemd160
  calculates the hash of this buffer correctly : 1000000 times - 3406ms
#ripemd160
  calculates the hash of this buffer correctly : 1000000 times - 1781ms
#sha512
  calculates the hash of this buffer correctly : 1000000 times - 1922ms
#sha512hmac
  calculates this known empty test vector correctly : 1000000 times - 11282ms
  calculates this known non-empty test vector correctly : 1000000 times - 12655ms
~~~

**Comment by monkeylord** [comment]
bs58 is back since it's size(2KB) does not matter actually.
However, for Hash, I added a switch in `lib/crypto/Hash.js`, so it use native hash in nodejs and use hash.js in browser.

**Comment by ryanxcharles** [comment]
that's a great solution.

there is now one new issue though, which is that the tests only cover the node hash functions and not the browser hash functions.

there are two ways to fix this. the simplest way is to just clone the hash function tests for each file.

the other way is to add back the browser tests which i removed. i removed them because they were broken, but if we're going to start making things different between node and the browser, maybe we should add them back (and fix them).

**Comment by monkeylord** [comment]
Not quite sure how to do browser tests.
What if we see it as an alternative?
Actually the library between node and browser are still same, but it choose to use hash.js if it's in browser.
The reference of node crypto is still there as a external library, but never used in browser.

**Comment by monkeylord** [comment]
Added hash.browser test.

**Pull request merged**
